### ISSUE TITLE
Returning Cached requests is missing from the Documentation

### ISSUE THREAD

**Issue by alionour** [gmpassos/mercury_client#1]
`Documentation` and  example missed to document how to request cached requests on network unavailable status or occurrence of any error . 
So Documentation should be updated and so the example
Also I wonder if caching is supported on windows and other desktop platforms

**Comment by gmpassos** [comment]
Thanks to send an issue.

I have just published a new version: `mercury_client v2.0.3`:
- Fixed a small bug in `HttpCache`.
- Improved examples and the `README` file.

About how to work with errors, you just need to use a normal `try/catch` block.

About the support on Windows or other platforms: It works in any platform, since this is a memory cache totally based in Dart.
